Better feedback whilst installing/uninstalling packages

diff --git a/zulu-install b/zulu-install
--- a/zulu-install
+++ b/zulu-install
@@ -33,8 +33,6 @@ function _zulu_install_package() {
   cd "$base/packages"
   git clone --recursive $repo $package
 
-  zulu link $package
-
   packagefile="$base/config/packages"
   in_packagefile=$(cat $packagefile | grep -e '^'${package}'$')
   if [[ "$in_packagefile" = "" ]]; then
@@ -48,7 +46,7 @@ function _zulu_install_package() {
 # Zulu command to handle package installation
 ###
 function _zulu_install() {
-  local base index packages
+  local base index packages out
 
   # Parse options
   zparseopts -D h=help -help=help
@@ -63,14 +61,23 @@ function _zulu_install() {
   base=${ZULU_DIR:-"$HOME/.config/zulu"}
   index="${base}/.index"
 
-  # If no context is passed, output the contents of the pathfile
-  if [[ "$1" = "" ]]; then
+  packages=($@)
+  packagefile="$base/config/packages"
+
+  # If no context is passed, install the contents of the packagefile
+  if [[ ${#packages} -eq 0 ]]; then
+    packages=($(cat $packagefile))
+  fi
+
+  if [[ ${#packages} -eq 0 ]]; then
     echo $(color red "Please specify a package name")
+    echo
+    _zulu_install_usage
     return 1
   fi
 
   # Do a first loop, to ensure all packages exist
-  for package in "$@"; do
+  for package in "$packages[@]"; do
     if [[ ! -f "$index/$package" ]]; then
       echo $(color red "Package '$package' is not in the index")
       return 1
@@ -78,7 +85,19 @@ function _zulu_install() {
   done
 
   # Do a second loop, to do the actual install
-  for package in "$@"; do
-    _zulu_install_package "$package"
+  for package in "$packages[@]"; do
+    _zulu_spinner_start "Installing $package..."
+    out=$(_zulu_install_package "$package" 2>&1)
+
+    if [ $? -eq 0 ]; then
+      _zulu_spinner_stop
+      echo "$(color green '✔') Finished installing $package        "
+    else
+      _zulu_spinner_stop
+      echo "$(color red '✘') Error installing $package        "
+      echo "$out"
+    fi
+
+    zulu link $package
   done
 }
diff --git a/zulu-uninstall b/zulu-uninstall
--- a/zulu-uninstall
+++ b/zulu-uninstall
@@ -23,8 +23,6 @@ function _zulu_uninstall_package() {
     return 1
   fi
 
-  zulu unlink $package
-
   # Remove the package source
   #
   # TODO: Obviously, this works, but would really like to find a pure-zsh
@@ -33,7 +31,7 @@ function _zulu_uninstall_package() {
   rm -rf "$root"
 
   packagefile="$base/config/packages"
-  echo $(cat $packagefile | grep -v -e '^'${package}'$') >! $packagefile
+  cat $packagefile | grep -v -e "^${package}$" >! $packagefile
 
   return
 }
@@ -42,7 +40,7 @@ function _zulu_uninstall_package() {
 # Zulu command to handle package installation
 ###
 function _zulu_uninstall() {
-  local base index packages
+  local base index packages out
 
   # Parse options
   zparseopts -D h=help -help=help
@@ -75,6 +73,18 @@ function _zulu_uninstall() {
 
   # Do a second loop, to do the actual install
   for package in "$@"; do
-    _zulu_uninstall_package "$package"
+    zulu unlink $package
+
+    _zulu_spinner_start "Uninstalling $package..."
+    out=$(_zulu_uninstall_package "$package" 2>&1)
+
+    if [ $? -eq 0 ]; then
+      _zulu_spinner_stop
+      echo "$(color green '✔') Finished uninstalling $package        "
+    else
+      _zulu_spinner_stop
+      echo "$(color red '✘') Error uninstalling $package        "
+      echo "$out"
+    fi
   done
 }
