Add --ignore-dependencies option

diff --git a/commands/install b/commands/install
--- a/commands/install
+++ b/commands/install
@@ -6,6 +6,9 @@
 function _zulu_install_usage() {
   echo $(_zulu_color yellow "Usage:")
   echo "  zulu install <packages...>"
+  echo
+  echo $(_zulu_color yellow "Options:")
+  echo "      --ignore-dependencies       Don't automatically install dependencies"
 }
 
 ###
@@ -47,10 +50,11 @@ function _zulu_install_package() {
 # Zulu command to handle package installation
 ###
 function _zulu_install() {
-  local base index packages out
+  local base index packages out help ignore_dependencies
 
   # Parse options
-  zparseopts -D h=help -help=help
+  zparseopts -D h=help -help=help \
+    -ignore-dependencies=ignore_dependencies
 
   # Output help and return if requested
   if [[ -n $help ]]; then
@@ -91,28 +95,30 @@ function _zulu_install() {
     # Get the JSON from the index
     json=$(cat "$index/$package")
 
-    # Get the list of dependencies from the index
-    dependencies=($(echo $(jsonval $json 'dependencies') | tr "," "\n" | sed 's/\[//g' | sed 's/\]//g'))
+    if [[ -z $ignore_dependencies ]]; then
+      # Get the list of dependencies from the index
+      dependencies=($(echo $(jsonval $json 'dependencies') | tr "," "\n" | sed 's/\[//g' | sed 's/\]//g'))
 
-    # If there are dependencies in the list
-    if [[ ${#dependencies} -ne 0 ]]; then
-      # Loop through each of the dependencies
-      for dependency in "$dependencies[@]"; do
-        # Check that the dependency is not already installed
-        if [[ ! -d "$base/packages/$dependency" ]]; then
-          _zulu_revolver start "Installing dependency $dependency..."
-          out=$(_zulu_install_package "$dependency" 2>&1)
-          _zulu_revolver stop
+      # If there are dependencies in the list
+      if [[ ${#dependencies} -ne 0 ]]; then
+        # Loop through each of the dependencies
+        for dependency in "$dependencies[@]"; do
+          # Check that the dependency is not already installed
+          if [[ ! -d "$base/packages/$dependency" ]]; then
+            _zulu_revolver start "Installing dependency $dependency..."
+            out=$(_zulu_install_package "$dependency" 2>&1)
+            _zulu_revolver stop
 
-          if [ $? -eq 0 ]; then
-            echo "$(_zulu_color green '✔') Finished installing dependency $dependency        "
-            zulu link $dependency
-          else
-            echo "$(_zulu_color red '✘') Error installing dependency $dependency        "
-            echo "$out"
+            if [ $? -eq 0 ]; then
+              echo "$(_zulu_color green '✔') Finished installing dependency $dependency        "
+              zulu link $dependency
+            else
+              echo "$(_zulu_color red '✘') Error installing dependency $dependency        "
+              echo "$out"
+            fi
           fi
-        fi
-      done
+        done
+      fi
     fi
 
     _zulu_revolver start "Installing $package..."
